/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Dominio.Registro;
import Servicio.Fachada;
import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import com.panamahitek.PanamaHitek_MultiMessage;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;

/**
 *
 * @author Usuario1
 */
public class jfrmModificar extends javax.swing.JFrame {

    Fachada fachada;
    PanamaHitek_Arduino ino = new PanamaHitek_Arduino();

 private void arduino(){

  
        
        PanamaHitek_MultiMessage multi = new PanamaHitek_MultiMessage(2, ino);
        SerialPortEventListener listener = new SerialPortEventListener() {
            @Override
            public void serialEvent(SerialPortEvent spe) {
                try {
                    if (multi.dataReceptionCompleted()) {
                        jTextPRE.setText(multi.getMessage(0));
                        jTextTMP.setText(multi.getMessage(1));
                        multi.flushBuffer();
                       
                    }
                } catch (ArduinoException | SerialPortException ex) {
                   Logger.getLogger(jfrmOpciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
         try {
            ino.arduinoRX("COM3", 9600, listener);
        } catch (ArduinoException ex) {
            Logger.getLogger(jfrmAgregar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(jfrmAgregar.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
    
    public jfrmModificar() {
        initComponents();
        fachada = Fachada.getInstancia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblModificar = new javax.swing.JLabel();
        jlblHora = new javax.swing.JLabel();
        jbtnGuardar = new javax.swing.JButton();
        txtTipoPrecipitacion = new javax.swing.JTextField();
        txtDepartamento = new javax.swing.JTextField();
        jlblTipoPrecipitacion = new javax.swing.JLabel();
        jlblDepartamento = new javax.swing.JLabel();
        jlblFecha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnVolver = new javax.swing.JButton();
        jCalendarMod = new com.toedter.calendar.JDateChooser();
        jtxtHora = new javax.swing.JTextField();
        jtxtMinutos = new javax.swing.JTextField();
        jlblDosPuntos = new javax.swing.JLabel();
        jTextPRE = new javax.swing.JTextField();
        jTextTMP = new javax.swing.JTextField();
        jbtntomardatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblModificar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jlblModificar.setText("Modificar");

        jlblHora.setText("Hora:");

        jbtnGuardar.setText("Guardar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });

        txtTipoPrecipitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoPrecipitacionActionPerformed(evt);
            }
        });

        jlblTipoPrecipitacion.setText("Tipo de precipitación:");

        jlblDepartamento.setText("Departamento:");

        jlblFecha.setText("Fecha:");

        jbtnVolver.setText("Volver");
        jbtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVolverActionPerformed(evt);
            }
        });

        jlblDosPuntos.setText(":");

        jTextPRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPREActionPerformed(evt);
            }
        });

        jbtntomardatos.setText("Tomar datos del arduino");
        jbtntomardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntomardatosActionPerformed(evt);
            }
        });

        jLabel1.setText("Temperatura");

        jLabel2.setText("Precipitaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jlblModificar)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnVolver)
                .addGap(224, 224, 224)
                .addComponent(jbtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblFecha)
                            .addComponent(jlblHora))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalendarMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlblDosPuntos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblDepartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblTipoPrecipitacion)
                        .addGap(18, 18, 18)
                        .addComponent(txtTipoPrecipitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel7)
                        .addContainerGap(100, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextTMP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextPRE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jbtntomardatos)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblModificar)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblDepartamento)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlblTipoPrecipitacion)
                                    .addComponent(txtTipoPrecipitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jlblFecha))
                            .addComponent(jCalendarMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlblDosPuntos))
                            .addComponent(jlblHora)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextPRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtntomardatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnVolver))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
 int dia = jCalendarMod.getCalendar().get(Calendar.DAY_OF_MONTH);
        int mes = jCalendarMod.getCalendar().get(Calendar.MONTH) + 1;
        int año = jCalendarMod.getCalendar().get(Calendar.YEAR);
        int id, hora, minutos, id_baja = -200000;
        double temperatura, precipitacion;
        String departamento, tipo_precipitacion;
        ArrayList unaLista = (ArrayList) fachada.getRegistroCRUD().Registros();
        if (unaLista.isEmpty()) {
            id = 1;
        } else {
            for (int i = 0; i < unaLista.size(); i++) {
                Registro tmpReg = (Registro) unaLista.get(i);
                if (id_baja < tmpReg.getId()) {
                    id_baja = tmpReg.getId();
                }
            }
            id = id_baja + 1;
        }

        if (this.txtDepartamento.getText().equals("artigas") || this.txtDepartamento.getText().equals("canelones") || this.txtDepartamento.getText().equals("cerro largo") || this.txtDepartamento.getText().equals("colonia") || this.txtDepartamento.getText().equals("durazno") || this.txtDepartamento.getText().equals("flores") || this.txtDepartamento.getText().equals("florida") || this.txtDepartamento.getText().equals("lavalleja") || this.txtDepartamento.getText().equals("maldonado") || this.txtDepartamento.getText().equals("montevideo") || this.txtDepartamento.getText().equals("paysandu") || this.txtDepartamento.getText().equals("rio negro") || this.txtDepartamento.getText().equals("rivera") || this.txtDepartamento.getText().equals("rocha") || this.txtDepartamento.getText().equals("salto") || this.txtDepartamento.getText().equals("san jose") || this.txtDepartamento.getText().equals("soriano") || this.txtDepartamento.getText().equals("tacuarembo") || this.txtDepartamento.getText().equals("treinta y tres")) {
            if (this.txtTipoPrecipitacion.getText().equals("lluvia") || this.txtTipoPrecipitacion.getText().equals("llovizna") || this.txtTipoPrecipitacion.getText().equals("nieve") || this.txtTipoPrecipitacion.getText().equals("aguanieve") || this.txtTipoPrecipitacion.getText().equals("granizo")){
            departamento = this.txtDepartamento.getText();
            tipo_precipitacion = this.txtTipoPrecipitacion.getText();
            hora = Integer.parseInt(this.jtxtHora.getText());
            minutos = Integer.parseInt(this.jtxtMinutos.getText());
            temperatura = Double.parseDouble(jTextTMP.getText());
            precipitacion = Double.parseDouble(jTextPRE.getText());
            if (hora > 23 || hora < 0 || minutos > 59 || minutos < 0) {
                JOptionPane.showMessageDialog(null, "ERROR  en la hora");
            } else {
                Registro unReg = new Registro(id, departamento, tipo_precipitacion, dia, mes, año, hora, minutos, precipitacion, temperatura);
                fachada.getRegistroCRUD().Guardar(unReg);
                JOptionPane.showMessageDialog(null, "Registro Guardado");
                jfrmOpciones unFrm = new jfrmOpciones();
                unFrm.setVisible(true);
                this.setVisible(false);
            }
            try {
                ino.killArduinoConnection();
            } catch (ArduinoException ex) {
                Logger.getLogger(jfrmAgregar.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese correctamente el tipo de precipitación");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese correctamente el nombre del departamento");
        }
        
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void txtTipoPrecipitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoPrecipitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoPrecipitacionActionPerformed

    private void jbtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVolverActionPerformed
        jfrmBuscarModificar unFrm=new jfrmBuscarModificar();
        unFrm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnVolverActionPerformed

    private void jTextPREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPREActionPerformed

    private void jbtntomardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntomardatosActionPerformed
        // TODO add your handling code here:
        arduino();
    }//GEN-LAST:event_jbtntomardatosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jCalendarMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextPRE;
    private javax.swing.JTextField jTextTMP;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnVolver;
    private javax.swing.JButton jbtntomardatos;
    private javax.swing.JLabel jlblDepartamento;
    private javax.swing.JLabel jlblDosPuntos;
    private javax.swing.JLabel jlblFecha;
    private javax.swing.JLabel jlblHora;
    private javax.swing.JLabel jlblModificar;
    private javax.swing.JLabel jlblTipoPrecipitacion;
    private javax.swing.JTextField jtxtHora;
    private javax.swing.JTextField jtxtMinutos;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtTipoPrecipitacion;
    // End of variables declaration//GEN-END:variables
}
